---

- name: Copy desktop wallpaper
  win_copy:
    src: DesktopWallpaper.png
    dest: C:\Users\Public\Pictures\DesktopWallpaper.png

- name: Copy bginfo configuration
  win_copy:
    src: bginfo.bgi
    dest: C:\Users\Public\bginfo.bgi

# Note: Chocolatey packages should be minimized to avoid hitting the rate limit (only 1 outbound IP is used)
- name: Install utilities 
  ignore_errors: yes
  win_chocolatey:
    name:
    - GoogleChrome
    - bginfo
    state: present
    ignore_checksums: true

- name: Configure bginfo as autorun
  win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
    name: bginfo
    data: 'C:\ProgramData\chocolatey\bin\bginfo.exe c:\users\public\bginfo.bgi /silent /timer:0 /nolicprompt'

- name: Ensure 'Search' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: SearchboxTaskbarMode
    data: 0
    type: dword

- name: Ensure 'News and Interests' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds
    name: EnableFeeds
    data: 0
    type: dword
    state: present

- name: Ensure 'People' unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People
    name: PeopleBand
    data: 0
    type: dword

- name: Ensure 'Edge', 'Store' other built-in shortcuts unpinned from the taskbar
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband
    name: Favorites
    state: absent

- name: Hide Task View, Chat and Cortana, always show file extensions
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowCortanaButton
    - ShowTaskViewButton
    - TaskbarDa
    - TaskbarMn
    - HideFileExt