---

# Join domain
- name: Configure DNS settings
  win_dns_client:
      adapter_names: Ethernet
      ipv4_addresses:
      - 10.13.37.10
      - 8.8.8.8

- name: Join machine to domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ ansible_user }}@{{ domain_name }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state

- name: Reboot after joining domain
  win_reboot:
  when: domain_state.reboot_required